version: '0.1.0'

services:
  django-backend:
    build: ./campus_connect_backend
    command: python manage.py runserver 0.0.0.0:8000
    image: django-campus-connect-backend
    container_name: django-campus-connect-backend
    ports:
      - "8000:8000"

  nuxt-frontend:
    build: ./campus-connect
    command: npm run dev
    image: next-campus-connect-frontend
    container_name: next-campus-connect-frontend
    ports:
      - "3000:3000"